package minetweaker.api.chat;

import org.openzen.zencode.annotations.OperatorType;
import org.openzen.zencode.annotations.ZenClass;
import org.openzen.zencode.annotations.ZenOperator;

/**
 * Represents a chat message. Strings can be converted into chat messages,
 * and chat messages can be colored and concatenated.
 * 
 * @author Stan Hebben
 */
@ZenClass("minetweaker.chat.IChatMessage")
public interface IChatMessage {
	/**
	 * Concatenates two chat messages.
	 * 
	 * @param other other chat message
	 * @return concatenated chat message
	 */
	@ZenOperator(OperatorType.ADD)
	public IChatMessage add(IChatMessage other);
	
	/**
	 * Retrieves the internal object backing this object. Must be generated by the
	 * implementing platform.
	 * 
	 * @return internal object
	 */
	public Object getInternal();
}
