/*
 * This file is part of MineTweaker API, licensed under the MIT License (MIT).
 * 
 * Copyright (c) 2014 MineTweaker <http://minetweaker3.powerofbytes.com>
 */
package minetweaker;

import java.util.List;

/**
 * The class registry provides the list of annotated classes to the scripting
 * system.
 *
 * API status: not a public API
 * 
 * @author Stan Hebben
 */
public class ClassRegistry
{
	public static void getClasses(List<Class> output)
	{
		// method stub; contents generated by RegisterZenClassesTask
	}
}
